from collections.abc import Callable
from datetime import datetime
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from labserver_core.domain.entities import ManagedServer, Reservation, TaskRequest, User


class UserRepositoryPort(Protocol):
    def get(self, user_id: UUID) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def add(self, user: User) -> None: ...
    def list_all(self) -> list[User]: ...


class ServerRepositoryPort(Protocol):
    def get(self, server_id: UUID) -> ManagedServer | None: ...
    def get_by_key(self, key: str) -> ManagedServer | None: ...
    def add(self, server: ManagedServer) -> None: ...
    def save(self, server: ManagedServer) -> None: ...
    def list_all(self) -> list[ManagedServer]: ...


class RequestRepositoryPort(Protocol):
    def get(self, request_id: UUID) -> TaskRequest | None: ...
    def add(self, task_request: TaskRequest) -> None: ...
    def list_for_user(self, user_id: UUID) -> list[TaskRequest]: ...
    def list_all(self) -> list[TaskRequest]: ...


class ReservationRepositoryPort(Protocol):
    def get_by_request_id(self, request_id: UUID) -> Reservation | None: ...
    def add(self, reservation: Reservation) -> None: ...
    def list_for_server(
        self, server_id: UUID, start: datetime, end: datetime
    ) -> list[Reservation]: ...
    def list_window(self, start: datetime, end: datetime) -> list[Reservation]: ...


class UnitOfWork(Protocol):
    users: UserRepositoryPort
    servers: ServerRepositoryPort
    requests: RequestRepositoryPort
    reservations: ReservationRepositoryPort

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


UnitOfWorkFactory = Callable[[], UnitOfWork]
