from collections.abc import Callable
from datetime import datetime
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from labserver_core.domain.entities import (
    AuditEvent,
    ManagedServer,
    PlanEntry,
    User,
)


class UserRepositoryPort(Protocol):
    def get(self, user_id: UUID) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def add(self, user: User) -> None: ...
    def list_all(self) -> list[User]: ...


class ServerRepositoryPort(Protocol):
    def get(self, server_id: UUID) -> ManagedServer | None: ...
    def get_by_key(self, key: str) -> ManagedServer | None: ...
    def add(self, server: ManagedServer) -> None: ...
    def save(self, server: ManagedServer) -> None: ...
    def list_all(self) -> list[ManagedServer]: ...


class PlanRepositoryPort(Protocol):
    def get(self, plan_id: UUID) -> PlanEntry | None: ...
    def add(self, plan: PlanEntry) -> None: ...
    def save(self, plan: PlanEntry) -> None: ...
    def list(
        self,
        *,
        server_id: UUID | None = None,
        owner_id: UUID | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
        include_cancelled: bool = False,
    ) -> list[PlanEntry]: ...


class AuditRepositoryPort(Protocol):
    def add(self, event: AuditEvent) -> None: ...
    def list_for_entity(self, entity_type: str, entity_id: UUID) -> list[AuditEvent]: ...


class UnitOfWork(Protocol):
    @property
    def users(self) -> UserRepositoryPort: ...

    @property
    def servers(self) -> ServerRepositoryPort: ...



    @property
    def plans(self) -> PlanRepositoryPort: ...

    @property
    def audits(self) -> AuditRepositoryPort: ...

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


UnitOfWorkFactory = Callable[[], UnitOfWork]
